// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/*";
  };
  "routes/home/route.tsx": {
    id: "routes/home/route";
    page: "/";
  };
  "routes/catchall/route.tsx": {
    id: "routes/catchall/route";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/home/route": typeof import("./src/routes/home/route.tsx");
  "routes/catchall/route": typeof import("./src/routes/catchall/route.tsx");
};